# -*- coding: utf-8 -*-
"""app_rm_simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129ewULH1aD-r_c1ZIpcsQy_eVy40tPH3
"""

import streamlit as st
import numpy as np

# Definindo as faixas de tarifas
tarifas = np.arange(300, 420, 10)

# Função para mapear ocupação para uma faixa de tarifa
def mapear_tarifa_ocupacao(ocupacao):
    indice = min(int(ocupacao // 10), len(tarifas) - 1)
    return tarifas[indice]

# Interface do Streamlit
st.title("Sugestão de Tarifa por Ocupação")

# Entrada de ocupação
ocupacao = st.number_input("Digite a ocupação (%)", min_value=0, max_value=100, step=1)

# Botão para gerar a tarifa
if st.button("Prever Tarifa"):
    tarifa_sugerida = mapear_tarifa_ocupacao(ocupacao)
    st.success(f"A tarifa sugerida é: R$ {tarifa_sugerida},00")